### ISSUE TITLE
It is possible to add a book multiple times for a singe user

### ISSUE THREAD

**Issue by Oyvindkg** [CrowdShelf/server#1]
http://crowdshelf.herokuapp.com/api/book/9780130920713

**Response:**
[{"_id":"55e5a15bfe92901100762078","owner":"ABFKAJEb432j#$jkb","isbn":"9780130920713","avaliableForRent":1,"numberOfCopies":1,"rentedTo":[]},{"_id":"55e5a43cfe92901100762079","owner":"ABFKAJEb432j#$jkb","isbn":"9780130920713","avaliableForRent":1,"numberOfCopies":1,"rentedTo":[]}]

**Comment by essoen** [comment]
Track on JIRA probably?
